name: Coverage

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        redis-version: [6]

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start Redis
      uses: supercharge/redis-github-action@1.5.0
      with:
        redis-version: ${{ matrix.redis-version }}

    - run: npm ci
    - run: npm run build
    - run: npm test
    - run: npm i coverage-badges-cli -g
    - run: coverage-badges --output docs/static/badge-coverage.svg
    - run: mkdir -p docs/content
    - run: cp README.md docs/content/_index.md

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.110.0'

    - name: Build
      run: cd docs && hugo --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/public